### ISSUE TITLE
`Merk::apply` method to take `BTreeMap<Key, Op>` instead of `&[(Key, Op)]`

### ISSUE THREAD

**Issue by larry0x** [nomic-io/merk#63]
Currently, the `Merk::apply` method takes a slice `&[(Key, Op)]`, where `Key = Vec<u8>`, checks the keys are **sorted and unique**, then invokes the unsafe method `apply_unchecked`. This check incurs an overhead.

I think a good idea is that `apply` method takes a `BTreeMap<Key, Op>` instead, which naturally guarantees the keys be sorted and unique, makes the check no longer necessary, and the method no longer needs to be unsafe.

Additionally: in [our project](https://github.com/CosmWasm/cw-multi-test/blob/v0.16.0/src/transactions.rs#L36), we already keep track of uncommitted changes in a BTreeMap indexed by keys. Under the current implementation, we have to first cast it into a slice before passing into `apply`, which incurs an overhead. If `apply` takes a BTreeMap instead, we can simply pass the map, removing this overhead.

Relevant code: https://github.com/nomic-io/merk/blob/8009dff26de5718eec709d3aea6d71f7c5188adb/src/merk/mod.rs#L134-L137

**Comment by mappum** [comment]
The reason `apply` takes a slice of ops is because internally the algorithms which modify the tree recursively split the batch into subslices and pass them along without having to copy any data. If a `BTreeMap` was passed in, it would have to be iterated over and collected into a vec anyway since we can't trivially pass along specific subtrees.

It seems like a good idea that you're keeping track of the batch as a `BTreeMap`, but I don't think the Merk API should take it in directly since we can't get around the step of iterating over it. Since you know all the keys are sorted and unique, you can at least skip the check in `apply` and just call `apply_unchecked` (which shouldn't really be unsafe because there are no memory safety issues, it's enough that the naming convention says "unchecked").

**Comment by larry0x** [comment]
@mappum makes sense! Thanks for the clarification.
